api/zuman/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class EditClauseForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=100)])
    content = TextAreaField("Inclause", validators=[DataRequired(), Length(min=2)])
    submit = SubmitField("Update")


class InclauseForm(FlaskForm):
    inputdata = TextAreaField("Input list", validators=[DataRequired(), Length(min=2)])
    submit = SubmitField("Make In Clause")

api/zuman/posts/routes.py
from datetime import datetime

from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from zuman import appdata, db
from zuman.models import Post
from zuman.posts.forms import EditClauseForm, InclauseForm
from zuman.posts.utils import inclauserator
from zuman.utils import validate_session

posts = Blueprint('posts', __name__)


@posts.route("/inclause", methods=["GET", "POST"])
def inclause():
    validate_session()
    page = request.args.get('page', 1, type=int)
    form = InclauseForm()
    appdata["title"] = "In-Clause App"
    op = None
    if form.validate_on_submit():
        op = inclauserator(form.inputdata.data)
    if current_user.is_authenticated:
        appdata['posts'] = Post.query\
            .filter_by(author=current_user)\
            .order_by(Post.date_accessed.desc())\
            .paginate(per_page=5, page=page)
    else:
        flash("Consider logging in to save your in-clause history.", "info")
    return render_template("posts/inclause.html", data=op, form=form, appdata=appdata)


@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
@login_required
def post(post_id):
    validate_session()
    form = EditClauseForm()
    postp = Post.query.get_or_404(post_id)
    if postp.author != current_user:
        abort(403)
    if form.validate_on_submit():
        postp.title = form.title.data
        postp.content = form.content.data
        postp.date_accessed = datetime.utcnow()
        db.session.commit()
        flash("This inclause has been updated.", "success")
        return redirect(url_for('posts.inclause'))
    appdata['title'] = postp.title
    appdata['legend'] = 'Update clause'
    form.title.data = postp.title
    form.content.data = postp.content
    return render_template('posts/post.html', appdata=appdata, form=form, post=postp)


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    validate_session()
    postp = Post.query.get_or_404(post_id)
    if postp.author != current_user:
        abort(403)
    db.session.delete(postp)
    db.session.commit()
    flash("This inclause has been deleted.", "success")
    return redirect(url_for('posts.inclause'))

api/zuman/templates/posts/inclause.html
{%extends 'layout.html'%}
{%block content%}
<div class="row mt-4">
    <div class="col-12 col-md-6">
        <div class="content-section">
            <form method="POST" action="{{url_for('posts.inclause')}}">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom">SQL In Clause Maker</legend>
                    <div class="form-group row">
                        <div class="text-md-right col-md-2">
                            {{form.inputdata.label(class="col-form-label", rows="15")}}
                        </div>
                        <div class="col-md-10">
                            {% if form.inputdata.errors %}
                            {{form.inputdata(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {%for error in form.inputdata.errors%}
                                <span>{{error}}</span>
                                {%endfor%}
                            </div>
                            {% else %}
                            {{form.inputdata(class="form-control", rows="15")}}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-form-label offset-md-2 col-md-10">
                            {{form.submit(class="btn btn-primary")}}
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    {% if current_user.is_authenticated and appdata['posts'].items %}
    <div class="col-12 col-md-6">
        {% for post in appdata['posts'].items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
                </div>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
        {% endfor %}
        {% for page_num in appdata['posts'].iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}
        {% if page_num %}
        {% if appdata['posts'].page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('posts.inclause', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.inclause', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <div class="col-12 col-md-6">
        {% include 'posts/jumbo.html' %}
    </div>
    {% endif %}
</div>
{%endblock content%}

api/zuman/templates/posts/jumbo.html
<div class="jumbotron">
    <div class="container content">
        {% if data %}
        {{data}}
        {% else %}
        <h1 class="jumbotron-heading">In Clause Maker tool</h1>
        <p class="lead">This tool helps you to create an in-clause for a list of input separated by new line characters.
        </p>
        <p>This in-clause is used by most Database Administrators and Developers for their sql queries.</p>
        <p>For example,</p>
        <p>Input list =></p>
        <p>abc<br>xyz</p>
        <p>Output In-clause => in ('abc','xyz')</p>
        <p>Note: This tool also accounts for Oracle database's 1000 entry limit for a clause. So if you input more
            than a 1000 entries, they will be divided in sections of 1000s.</p>
        {% endif %}
    </div>
</div>

api/zuman/templates/posts/post.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
  <div class="content-section">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ appdata['legend'] }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
        {{ form.content(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
      {{ form.submit(class="btn btn-info") }}
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input class="btn btn-danger" type="submit" value="Delete"
            formaction="{{ url_for('posts.delete_post', post_id=post.id) }}">
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}