api/zuman/users/routes.py
import logging
import os

from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_required, login_user
from zuman import appdata, bcrypt, db
from zuman.models import User, default_pic
from zuman.users.forms import (LoginForm, RegistrationForm, RequestResetForm,
                               ResetPasswordForm, UpdateAccountForm)
from zuman.users.utils import save_picture, send_reset_email
from zuman.utils import logout as logout_user
from zuman.utils import set_session, validate_session

users = Blueprint('users', __name__)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    appdata["title"] = "Log In"
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            set_session()
            logging.info(f"> login {current_user.username} ...")
            flash("You have been logged in!", "success")
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(
                url_for("posts.inclause"))
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("users/login.html", appdata=appdata, form=form)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    appdata["title"] = "Register new account"
    if form.validate_on_submit():
        session.clear()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}! Please log in.",
              "info")
        return redirect(url_for("users.login"))
    return render_template("users/register.html", appdata=appdata, form=form)


@users.route("/logout")
def logout():
    logging.info(f"> logout {current_user.username} ...")
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    validate_session()
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        old_pic = current_user.image_file
        if form.picture.data:
            pic_file = save_picture(form.picture.data)
            current_user.image_file = pic_file
            if old_pic != default_pic:
                old_pic = os.path.join(
                    os.path.abspath(__file__ + "../../.."), 'static/profile_pics', old_pic)
                if os.path.isfile(old_pic):
                    os.remove(old_pic)
        db.session.commit()
        flash('Your account is updated', 'success')
        return redirect(url_for("users.account"))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    appdata["title"] = "Account"
    appdata['image_file'] = image_file
    return render_template("users/account.html", appdata=appdata, form=form)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email is sent with Password Reset link. Please check your Spam folder if you did not receive the email in your inbox.', 'info')
        return redirect(url_for('users.login'))
    appdata["title"] = "Reset Password"
    return render_template(
        'users/reset_request.html', appdata=appdata, form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash(f"Password updated successfully", "info")
        return redirect(url_for("users.login"))
    appdata["title"] = "Reset Password"
    return render_template('users/reset_token.html', appdata=appdata, form=form)

api/zuman/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='favicon/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='favicon/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='favicon/favicon-16x16.png')}}">
    <link rel="manifest" href="{{url_for('static', filename='favicon/site.webmanifest')}}">

    {%if appdata['title']%}
    <title>{{appdata['title']}}</title>
    {%elif session['title']%}
    <title>{{session['title']}}</title>
    {%else%}
    <title>{{appdata['website_name']}}</title>
    {%endif%}

    <script src="https://kit.fontawesome.com/7702e7e847.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"
        integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous" />
    <link href="{{url_for('static', filename='stimulus/css/templatemo-style.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{url_for('static', filename='layout.css')}}" rel="stylesheet" type="text/css" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700" rel="stylesheet">

</head>

<body data-spy="scroll" data-target=".navbar-collapse" data-offset="50">


    <!-- PRE LOADER -->

    <div class="preloader">
        <div class="spinner">
            <span class="spinner-rotate"></span>
        </div>
    </div>


    <!-- Navigation Section -->

    <nav class="navbar navbar-fixed-top fixed-top custom-navbar navbar-expand-md" role="navigation">
        <div class="container-fluid mx-2">

            <!-- navbar header -->
            <a href="/" class="navbar-brand"><i class="fas fa-bolt"></i> {{appdata['website_name']}}</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navToggler" aria-controls="navToggler"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" />
            </button>

            <div class="collapse navbar-collapse" id="navToggler">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link smoothScroll" href="/#contact">Contact</a>
                    <a class="nav-item nav-link smoothScroll" href="{{url_for('posts.inclause')}}">In-Clause</a>
                    <a class="nav-item nav-link smoothScroll" target="_blank" href="https://tradetaj.com">Tradetaj</a>
                </div>
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link smoothScroll" href="{{url_for('users.account')}}">Account</a>
                    <a class="nav-item nav-link smoothScroll" href="{{url_for('users.logout')}}">Log out</a>
                    {% else %}
                    <a class="nav-item nav-link smoothScroll" href="{{url_for('users.login')}}">Log In</a>
                    <a class="nav-item nav-link smoothScroll" href="{{url_for('users.register')}}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-2">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    {%if not no_container%}
    <div class="container">
        {% endif %}
        {%block content%}
        {%endblock content%}
        {%if not no_container%}
    </div>
    {% endif %}
    <!-- Footer Section -->

    <footer>
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12 col-sm-12">
                    <div class="wow fadeInUp footer-copyright" data-wow-delay="1.8s">
                        <p>Copyright &copy; 2024 Zuman's
                        </p>
                    </div>
                    <ul class="wow fadeInUp social-icon" data-wow-delay="2s">
                        <li><a target="_blank" href="https://twitter.com/zuman_one" class="fab fa-twitter"></a>
                        </li>
                        <li><a target="_blank" href="https://github.com/zuman" class="fab fa-github"></a></li>
                        <li><a target="_blank" href="https://www.instagram.com/zuman.one" class="fab fa-instagram"></a>
                        </li>
                        <li><a target="_blank" href="https://www.linkedin.com/in/zuman" class="fab fa-linkedin"></a>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>

    <!-- SCRIPTS -->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-parallax/1.1.3/jquery-parallax-min.js"
        integrity="sha256-+r9MHvpJMAqVrQNi6Qu29BYePHsoPhwt/FGxeaNkY7I=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/16.1.0/smooth-scroll.min.js"
        integrity="sha256-CfyPGYLRQ4v1O+mZa5ocQglABXGuaZmmfe8awy8Fxis=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"
        integrity="sha256-z6FznuNG1jo9PP3/jBjL6P3tvLMtSwiVAowZPOgo56U=" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='custom.js')}}"></script>

    {% if 'apage' in session['js'] %}
    <script src="{{url_for('static', filename='stimulus/js/apage.js', v=session['version'])}}"></script>
    {% endif %}

</body>

</html>